### ISSUE TITLE
Widget not initialized correctly with stochastic integrator

### ISSUE THREAD

**Issue by i-Zaak** [the-virtual-brain/tvb-widgets#61]
When stochastic integrator is provided in the constructor, the widget creation fails as the `noise_slider_valinit` is not set.

https://github.com/the-virtual-brain/tvb-widgets/blob/2437928f64914e693ef13c4d0ac4c4b11306a8ff/tvbwidgets/ui/phase_plane_widget.py#L512C73-L512C73

To reproduce:
```python
w = PhasePlaneWidget(integrator=integrators.HeunStochastic())
w.get_widget()
```

**Comment by liadomide** [comment]
We can reproduce this.

We are handling to give `noise_slider_valinit ` only for the case when the Integrator is set later (from the GUI), but when given in the constructor, we will have a problem.

We will propose a fix soon.
